
CUDA availability: True
Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 83, in main
    model_trained = train(dataset, config,  device)
  File "main.py", line 30, in train
    loader = DataLoader(dataset, batch_size=config.learning_rate, shuffle=True)
AttributeError: 'dict' object has no attribute 'learning_rate'