Traceback (most recent call last):
  File "main.py", line 87, in <module>
    main()
  File "main.py", line 83, in main
    model_trained = train(dataset, config,  device)
  File "main.py", line 44, in train
    for batch in loader:
  File "/home/dalab5/miniconda3/envs/GNN/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/dalab5/miniconda3/envs/GNN/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 557, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/dalab5/miniconda3/envs/GNN/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dalab5/miniconda3/envs/GNN/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dalab5/Projects/MA_packed/utils.py", line 52, in __getitem__
    return self.ma_dataset[idx]
IndexError: list index out of range
CUDA availability: True